django/access/access/apps/citas/urls.py
from django.conf.urls.defaults import patterns,url

urlpatterns = patterns('access.apps.citas.views',
    url(r'^citas/$','citas',name='citas_view'),

    url(r'^citas/vuelo/$','citas_vuelo',name='citas_vuelo_view'),
    url(r'^citas/usuario/$','citas_usuario',name='citas_usuario_view'),
    url(r'^citas/confirmada/$','citas_confirmada',name='citas_confirmada_view'),

    url(r'^citas.solicitar/$','crear_cita',name='solicita_citas_view'),
    url(r'^citas.accion/$','accion_citas',name='accion_cita_view'),
    url(r'^citas.editar/(\d{1,6})/$','edita_citas',name='accion_cita_view'),
    url(r'^citas.ver/$','ver_todas_citas',name='ver_todas_citas'),
    url(r'^citas.ver/(\d{1,6})/$','ver_una_cita',name='ver_una_cita'),
   
    url(r'^citas.vuelo/(\d{1,6})/$','add_vuelo',name='add_vuelo'),
    
    url(r'^citas.filtros/$','citas_filtros',name='get_citas_filtros'),
    url(r'^citas.filtros/all$','citas_filtros_all',name='get_citas_filtros_all'),
    
    url(r'^citas.confirma/(\d{1,6})/$','confirma_cita',name='confirma_cita_view'),

    url(r'^citas.calendario/$','calendario_citas',name='calendario_cita'),

)

django/access/access/apps/inicio/urls.py
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('access.apps.inicio.views',
	url(r'^$', 'inicio',name='vista_inicio'),
    url(r'^contact/$','contact_view',name='contact_view'),

)

django/access/access/apps/usuarios/urls.py
from django.conf.urls.defaults import patterns,url

urlpatterns = patterns('access.apps.usuarios.views',
	 url(r'^usuarios/registro/$','registro_usuarios',name='registro_usuarios_view'),
     url(r'^usuarios/login/$','login_view',name='view_login'),
     url(r'^usuarios/info.adicional/$','llenar_info_adicional',name='info_adicional_view'),
     url(r'^usuarios/logout/$','logout_view',name='logout_liga_view'),
)

django/access/access/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required
import settings
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'access.views.home', name='home'),
    # url(r'^access/', include('access.foo.urls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
	# Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    # Our url's apps
    url(r'^static/media/(?P<path>.*)$','django.views.static.serve',{'document_root':settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$','django.views.static.serve',{'document_root':settings.STATIC_ROOT}),
    # (r'^comments/', include('django.contrib.comments.urls')),

    #Import urls.py's apps 
    url(r'^',include('access.apps.inicio.urls')),
    url(r'^',include('access.apps.usuarios.urls')),
    url(r'^',include('access.apps.membresias.urls')),
    url(r'^',include('access.apps.citas.urls')),
    url(r'^',include('access.apps.actividades.urls')),

)

django/access/access/apps/actividades/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.



class actividad(models.Model):
	miembro   = models.ForeignKey(User,related_name='miembros')
	descripcion = models.TextField()
	fecha     = models.DateTimeField(auto_now_add=True)
	leido     = models.BooleanField(default=False)
	def __unicode__(self):
		return "%s" % self.fecha

django/access/access/apps/inicio/models.py
from django.db import models

# Create your models here.

django/access/access/apps/membresias/models.py
#encoding:utf-8
from django.db import models
from django.contrib.auth.models import User
from django import forms


class tipo_poliza(models.Model):
	tipo_poliza = models.CharField(max_length=150,verbose_name="Tipo de póliza")

	def __unicode__(self):
		return "%s" %self.tipo_poliza

	class Meta:
		verbose_name = "Tipo de Póliza"
		verbose_name_plural = "Tipos de Pólizas"

class tipo_cobertura(models.Model):
	cobertura = models.CharField(max_length=150,verbose_name="Tipo de cobertura")

	def __unicode__(self):
		return "%s" %self.cobertura

	class Meta:
		verbose_name = "Tipo de cobertura"
		verbose_name_plural = "Tipos de Coberturas"

	
class membresia(models.Model):
	''' Modelo para los diferentes tipos de membresia que tendra el sistema  [Individual,Familiar,Corporativo]'''
	membresia_tipo  = (("1","Personal"),("3","Corporativa"),)	
	sexo_tipo 		= (("Femenino","Femenino"),("Masculino","Masculino"),)
	''' Estos son los campos para la compra de la membresia '''
	tipo					= models.CharField(max_length=50,choices=membresia_tipo)
	
	nombre 					= models.CharField(null=False,blank=False, verbose_name='Nombre(s)', max_length=100)
	apellido_paterno 		= models.CharField(null=False,blank=False, verbose_name='Apellido Paterno', max_length=100)
	apellido_materno 	 	= models.CharField(null=False,blank=False, verbose_name="Apellido Materno", max_length=255)

	calle  					= models.CharField(verbose_name='Calle',max_length=100,null=True,blank=True)
	no_exterior				= models.CharField(verbose_name="No. Exterior",max_length=10,null=True,blank=True)
	no_interior	 			= models.CharField(verbose_name='No. Interior',max_length=10,blank=True,null=True)
	colonia					= models.CharField(verbose_name='Colonia',max_length=100,null=True,blank=True)
	municipio				= models.CharField(verbose_name='Delegación o Municipio',max_length=150,null=True,blank=True)
	ciudad					= models.CharField(verbose_name='Ciudad',max_length=100,null=True,blank=True)
	cp 						= models.IntegerField(verbose_name='CP.',null=True,blank=True)
	pais 					= models.CharField(verbose_name='País',max_length=150,null=True,blank=True)
	
	email 					= models.EmailField(null=False,blank=False, verbose_name='Email principal',max_length=200)
	re_email 		 		= models.EmailField(null=False,blank=False,verbose_name='Confirma tu Mail',max_length=200)
	
	area                    = models.CharField(verbose_name="Área internacinal",max_length=20,null=True,blank=True)
	lada				    = models.CharField(verbose_name='Clave Lada',max_length=20,null=True,blank=True)
	telefono				= models.CharField(verbose_name='Telefono',max_length=20,null=True,blank=True)

	''' Enlace a Miembro y Call Center '''
	call_center 			= models.ForeignKey(User,related_name='CallCenter',null=True,blank=True)
	miembro 	 			= models.ForeignKey(User,related_name='Miembro',null=True,blank=True)

	''' '''
	password 				= models.CharField(verbose_name='Contraseña',max_length=250)
	renovo_pass 			= models.BooleanField(default=False)
	online 					= models.BooleanField(default=False)
	padre                   = models.IntegerField(default=0,null=True,blank=True)

	fecha_registro			= models.DateField(auto_now_add=True)
	fecha_envio				= models.DateField(null=True,blank=True)
	fecha_recibo			= models.DateField(null=True,blank=True)
	activa 				    = models.BooleanField(default=False)
	pagada 					= models.BooleanField(default=False)
	activa_paquete  		= models.BooleanField(default=False)

	costo 					= models.FloatField(default=0,null=True,blank=True)

	class Meta:
		verbose_name = 'membresia'
		verbose_name_plural = 'membresias'
		
	def __unicode__(self):
		return "%s %s %s -- %s"%(self.nombre,self.apellido_paterno,self.apellido_materno, self.id) 

class MenoresEdad(models.Model):
	titular          = models.ForeignKey(User,related_name="Titulares")
	mem_titular      = models.ForeignKey(membresia,related_name="MemTitulares")
	nombre           = models.CharField(max_length=150,verbose_name="Nombre")
	apellido_paterno = models.CharField(max_length=150,verbose_name="Apellido Paterno")
	apellido_materno = models.CharField(max_length=150,verbose_name="Apellido Materno")
	fecha_nacimiento = models.DateField(verbose_name="Fecha de nacimiento")
	relacion 		 = models.CharField(null=True,blank=True,max_length=100,verbose_name="Relación con el titular")
	class Meta:
		verbose_name = 'Menor de edad'
		verbose_name_plural = 'Menores de edad'

	def __unicode__(self):
		return ("%s %s %s")%(self.nombre, self.apellido_materno,self.apellido_paterno)

class PaseMenor(models.Model):
	titular 		= models.ForeignKey(User,related_name='PasesTitulares')
	menor   		= models.ForeignKey(MenoresEdad,related_name='Pases',verbose_name="Seleccione el menor de edad")
	fecha_inicio    = models.DateField(auto_now_add=True) 
	fecha_fin   	= models.DateField() 
	
	def __unicode__(self):
		return ("%s %s %s")%(self.menor.nombre, self.menor.apellido_materno,self.menor.apellido_paterno)


class rel_mem(models.Model):
	titular      = models.ForeignKey(User,related_name="UsuarioTitular")
	mem_titular  = models.ForeignKey(membresia,related_name="MembresiaTitular")
	mem_referido = models.ForeignKey(membresia,related_name="MembresiaReferida")
	fecha_hora   = models.DateTimeField(auto_now_add=True)
	
	def __unicode__(self):
		return "%s %s -- %s" % (self.titular.first_name,self.titular.last_name,self.mem_referido)
	class Meta:
		verbose_name        = "Referidos Membresia"
		verbose_name_plural = "Sistema de Referidos"




class info_adicional(models.Model):
	''' Información requerida para la activación de las membresias. '''
	membresia 				= models.ForeignKey(membresia)
	
	compania_seguros	 	= models.CharField(max_length=255,verbose_name="Compañia de seguros")
	# Se quito direccion de compañia
	# direccion_compania	 	= models.TextField(blank=True,null=True,verbose_name="Dirección de la compañía de seguros")
	nombre_representante 	= models.CharField(max_length=255,verbose_name="Nombre del representante de compañía de seguros o intermediario",blank=True,null=True)
	telefono_representante 	= models.CharField(max_length=255,verbose_name="Telefono del representante de compañía de seguros",blank=True,null=True)
	 
	# Informacion de póliza
	poliza 					= models.CharField(max_length=255,verbose_name="Póliza")
	tipo_poliza 			= models.ForeignKey(tipo_poliza, verbose_name="Selecciona el tipo de póliza")
	tipo_cobertura 			= models.ForeignKey(tipo_cobertura, verbose_name="Selecciona el tipo de cobertura")
	# Se mostraran solo si selecionan la plabra otros dentro de los select anteriores
	tipo_poliza_otro 			= models.CharField(max_length=255,verbose_name="Tipo Póliza",blank=True,null=True)
	tipo_cobertura_otro 		= models.CharField(max_length=255,verbose_name="Tipo Cobertura | Plan",blank=True,null=True)
	fecha_vencimiento           = models.DateField(verbose_name="Fecha de Vencimiento")

	# Preguntar si son requeridos estos campos
	contacto_emergencia_usa  = models.CharField(max_length=255,verbose_name='Contacto de emergencia en USA',blank=True,null=True)
	telefono_contacto_usa    = models.CharField(verbose_name='Telefono del contacto en USA', max_length=50,blank=True,null=True)
	nombre_dr_mexico	     = models.CharField(verbose_name='Nombre de tu doctor en México', max_length=255,blank=True,null=True)
	telefono_dr_mexico	     = models.CharField(verbose_name='Teléfono de tu doctor en México', max_length=255,blank=True,null=True)
	info_adicional_tx_center = models.TextField(verbose_name='Información adicional solicitada por TX Medical Center',blank=True,null=True)

	# Tiene pasaporte, si no, esconde campos y no son requeridos
		# Se elemino la pregunta si tiene pasaporte o no.
	# tiene_pasaporte         = models.BooleanField(verbose_name="¿Tiene pasaporte?")
	no_pasaporte  		    = models.CharField(verbose_name='No. Pasaporte', max_length=255,blank=True,null=True)
		# vencimiento_pasaporte   = models.DateField(verbose_name='Fecha de vencimiento del pasaporte',blank=True,null=True)
	# Tiene visa? si no, oculta campos siguientes
	# tiene_visa  		    = models.BooleanField(verbose_name='¿Tiene VISA?', max_length=255)
	no_visa					= models.CharField(verbose_name='No. VISA', max_length=255,blank=True,null=True)
	# vencimiento_visa   		= models.DateField(verbose_name='Fecha de vencimiento de la VISA',blank=True,null=True)
	class Meta:
		verbose_name = 'Info. adicional para activación'
		verbose_name_plural = 'Información Adicional'
	
	def __unicode__(self):
		return "%s" %self.compania_seguros
    

class miembros_adicionales(models.Model):
	''' Modelo para la relación de miembros adicionales de cada titular de membresias '''
	sexo_tipo = (("Femenino","Femenino"),("Masculino","Masculino"),)

	membresia 			 	= models.ForeignKey(membresia,verbose_name="Seleccione la membresia",blank=True,null=True)

	nombre				 	= models.CharField(max_length=255,verbose_name="Nombre (s)")
	apellido_paterno 	 	= models.CharField(verbose_name="Apellido Paterno", max_length=255)
	apellido_materno 	 	= models.CharField(verbose_name="Apellido Materno", max_length=255)
	genero 				 	= models.CharField(verbose_name="Género", choices=sexo_tipo, max_length=10)
	nacionalidad		 	= models.CharField(max_length=100)
	fecha_nacimiento       	= models.DateField(verbose_name="Fecha de Nacimiento")
	parentesco			 	= models.CharField(max_length=255,verbose_name="¿Cúal es el parentesco con el titular de la membresia?")

	# Comparte Poliza? Si es False se muestran la info de captura de poliza.
	comparte_poliza      	= models.BooleanField(default=False)
	
	# Informacion del intermediario
	nombre_representante 	= models.CharField(max_length=255,verbose_name="Nombre del representante de compañía de seguros o intermediario",blank=True,null=True)
	telefono_representante 	= models.CharField(max_length=255,verbose_name="Telefono del representante de compañía de seguros",blank=True,null=True)
	# Información de póliza
	poliza 					= models.CharField(max_length=255,verbose_name="Póliza",blank=True,null=True)

django/access/access/apps/servicios/models.py
from django.db import models

# Create your models here.

django/access/access/apps/actividades/forms.py
from django import forms
from django.forms import ModelForm
from django.db import models
from django.forms import ModelChoiceField




# class frmCita(forms.ModelForm):
# 	class Meta:
# 		model = cita
# 		exclude = ['no_membresia','confirmada','socio','miembro','estado',]


# class frmCitaAvion(forms.ModelForm):
# 	class Meta:
# 		model = cita
# 		fields = ['info_vuelo',]

django/access/access/apps/citas/forms.py
#encoding:utf-8

from django import forms
from django.forms import ModelForm
from django.db import models
from django.forms import ModelChoiceField
from access.apps.citas.models import cita,Vuelo



class frmCita(forms.ModelForm):
	class Meta:
		model = cita
		exclude = ['recomendaciones','no_membresia','confirmada','socio','miembro','estado','fecha_confirmada']


class frmCitaAvion(forms.ModelForm):
	class Meta:
		model = cita
		fields = ['recomendaciones',]


class frmAddInfoVuelo(forms.ModelForm):
	class Meta:
		model = Vuelo
		exclude = ['Cita','Estado']

django/access/access/apps/inicio/forms.py
from django import forms


class ContactForm(forms.Form):
	Name  		= forms.CharField(widget=forms.TextInput())
	Email 		= forms.EmailField(widget=forms.TextInput())
	Subject 	= forms.CharField(widget=forms.TextInput())
	Content 	= forms.CharField(widget=forms.Textarea())

django/access/access/apps/actividades/views.py
#encoding:utf-8
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from django.http import HttpResponse , HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
#Modelos 
from django.contrib.auth.models import User
from access.apps.actividades.models import actividad
# Formularios

# Librerias / Herramientas
from django.core.mail import EmailMultiAlternatives 

@login_required
def actividades_all(request):
	objActividades = actividad.objects.filter(miembro=request.user).order_by('-fecha')
	ctx = {"acts":objActividades}
	return render_to_response('actividades/actividades.html',ctx,context_instance=RequestContext(request))


@login_required
def ver_actividad(request,idActividad):
	idAct = int(idActividad)
	objAct = get_object_or_404(actividad,pk=idAct)
	ctx = {"act":objAct}
	return render_to_response('actividades/actividad.html',ctx,context_instance=RequestContext(request))

django/access/access/apps/inicio/views.py
from django.shortcuts 			import render_to_response
from django.template  			import RequestContext
from django.core.mail 			import EmailMultiAlternatives 
from django.http				import HttpResponseRedirect
from access.apps.inicio.forms 	import ContactForm



def inicio(request):
	return render_to_response('inicio/home.html',context_instance=RequestContext(request))

def contact_view(request):
	info_send = False # Define si se envio la info o no se envio
	name   = ""
	email  = ""
	subject = ""
	content  = ""
	if request.method == "POST":
		objForm = ContactForm(request.POST)
		if objForm.is_valid():
			info_send  = True
			name    = objForm.cleaned_data['Name']
			email   = objForm.cleaned_data['Email']
			subject = objForm.cleaned_data['Subject']
			content = objForm.cleaned_data['Content']
			# Configuracion para envio de email por gmail
			to_admin = 'roberto@newemage.com'
			html_content = "Information received from <br>Name: [%s] <br> Email: [%s]  <br><br>***Message<br><br>%s"%(name,email,content)
			msg = EmailMultiAlternatives(subject,html_content,'from@server.com',[to_admin])
			msg.attach_alternative(html_content,'text/html') #Definimos el contenido como HTML
			msg.send() #enviamos el correo
	else:
		objForm = ContactForm()
	ctx = {'form':objForm,'name':name,'email':email,'subject':subject,'content':content,'info_send':info_send}
	return render_to_response('forms/contact/contact.html',ctx,context_instance=RequestContext(request))	

django/access/access/apps/servicios/views.py
# Create your views here.

django/access/access/templates/forms/membresia/compra.html
{% extends "base/template_base.html" %}

{% block title %} Compra de Membresia {% endblock %}

{% block contenido %}
	<div class="separador-slider visible-desktop"></div>
	<div class="container-fluid">
	    <div class="row-fluid">
	        
	        	<h1 class="mod-head"><span id="msg">Compra de membresia Call Center</span></h1>
	        	<div class="form-full">
				<form action="" method="POST">
					{% csrf_token %}
				<div class="span5">
				<fieldset>
					
				
				<!-- *********************************  -->
				<h3 class="mod-head">Nombre completo</h3>
								
				<div style="display:none;" class="control-group {% if form.tipo.errors %}error{% endif %}">
					<label class="control-label">
						{{form.tipo.label_tag}}
					</label>
					<div class="controls">
						{{ form.tipo }}
						{% if form.tipo.errors %}
							<span class="help-inline">{{form.tipo.errors}}</span>
						{% endif %}
					</div>
				</div>

				<div class="control-group {% if form.nombre.errors %}error{% endif %}">
					<label class="control-label {% if form.nombre.errors %}error{% endif %}">
						{{form.nombre.label_tag}}
					</label>
					<div class="controls">
						{{ form.nombre }}
						{% if form.nombre.errors %}
							<span class="help-inline">{{form.nombre.errors}}</span>
						{% endif %}
					</div>
				</div>

				<div class="control-group {% if form.apellido_paterno.errors %}error{% endif %}">
					<label class="control-label {% if form.apellido_paterno.errors %}error{% endif %}">
						{{form.apellido_paterno.label_tag}}
					</label>
					<div class="controls">
						{{ form.apellido_paterno }}
						{% if form.apellido_paterno.errors %}
							<span class="help-inline">{{form.apellido_paterno.errors}}</span>
						{% endif %}
					</div>
				</div>

				<div class="control-group {% if form.apellido_materno.errors %}error{% endif %}">
					<label class="control-label {% if form.apellido_materno.errors %}error{% endif %}">
						{{form.apellido_materno.label_tag}}
					</label>
					<div class="controls">
						{{ form.apellido_materno }}
						{% if form.apellido_materno.errors %}
							<span class="help-inline">{{form.apellido_materno.errors}}</span>
						{% endif %}
					</div>
				</div>
			</div>
			
<div class="span5">
	<h3 class="mod-head">Datos de contacto</h3>
				<fieldset>


				<div class="control-group {% if form.email.errors %}error{% endif %}">
					<label class="control-label {% if form.email.errors %}error{% endif %}">
						{{form.email.label_tag}}
					</label>
					<div class="controls">
						{{ form.email }}
						{% if form.email.errors %}
							<span class="help-inline">{{form.email.errors}}</span>
						{% endif %}
					</div>
				</div>
				
				<div class="control-group {% if form.re_email.errors %}error{% endif %}">
					<label class="control-label {% if form.re_email.errors %}error{% endif %}">
						{{form.re_email.label_tag}}
					</label>
					<div class="controls">
						{{ form.re_email }}
						{% if form.re_email.errors %}
							<span class="help-inline">{{form.re_email.errors}}</span>
						{% endif %}
					</div>
				</div>

			<div class="position-two">
				
				<div class="control-group area {% if form.area.errors %}error{% endif %}">
					<label class="control-label {% if form.area.errors %}error{% endif %}">
						{{form.area.label_tag}}
					</label>
					<div class="controls">
						{{ form.area }}
						{% if form.area.errors %}
							<span class="help-inline">{{form.area.errors}}</span>
						{% endif %}
					</div>
				</div>
				<div class="control-group lada {% if form.lada.errors %}error{% endif %}">
					<label class="control-label {% if form.lada.errors %}error{% endif %}">
						{{form.lada.label_tag}}
					</label>
					<div class="controls">
						{{ form.lada }}
						{% if form.lada.errors %}
							<span class="help-inline">{{form.lada.errors}}</span>
						{% endif %}
					</div>
				</div>
				
			</div>				

			<div class="control-group {% if form.telefono.errors %}error{% endif %}">
					<label class="control-label {% if form.telefono.errors %}error{% endif %}">
						{{form.telefono.label_tag}}
					</label>
					<div class="controls">
						{{ form.telefono }}
						{% if form.telefono.errors %}
							<span class="help-inline">{{form.telefono.errors}}</span>
						{% endif %}
					</div>
				</div>
				</fieldset>
</div>


					<!--{{form.as_p}}-->
					<div class="full">
					<input type="reset" value="Limpiar" class="reset">
					<input type="submit" value="Comprar" Class="submit compra">
				</div>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock contenido %}
{% block extra_js %}

<script type="text/javascript">
function soloNumeros(evt){
	//asignamos el valor de la tecla a keynum
	if(window.event){// IE
		keynum = evt.keyCode;
	}else{
		keynum = evt.which;
	}
	//comprobamos si se encuentra en el rango
	if(keynum>47 && keynum<58){
		return true;
	}else{
		return false;
	}
}

function inicio()
{
	$("#id_tipo").val({{tipo}});
	var texto = $("#id_tipo").find("option:selected").text();
	$("#msg").html("Compra de membresia Call Center " + texto);

	$("#id_cp").attr("maxlength","5");
	$("#id_area").attr("maxlength","3");
	$("#id_lada").attr("maxlength","3");
	$("#id_telefono").attr("maxlength","8");


	$("#id_cp").on("keypress",function(e){
		return soloNumeros(e);
	});
	$("#id_lada").on("keypress",function(e){
		return soloNumeros(e);
	});
	$("#id_area").on("keypress",function(e){
		return soloNumeros(e);
	});
	$("#id_telefono").on("keypress",function(e){
		return soloNumeros(e);
	});
}
$(document).on("ready",inicio);



</script>	
{% endblock extra_js %}

django/access/access/templates/forms/membresia/login_activa.html
{% extends "base/template_base.html" %}

{% block title %} Compra de Membresia {% endblock %}

{% block contenido %}
	<div class="separador-slider visible-desktop"></div>
	<div class="container">
	    <div class="row">
	        <div class="span12">
	        	<h1 class="mod-head"><span>Activa tu membresía</span></h1>
	        	<br><br>
				<form action="" method="POST">
					<strong>{{ mensaje }} <br></strong>
					{% csrf_token %}
					{{frmActiva.as_p}}
					<input type="reset" value="Limpiar" class="reset">
					<input type="submit" value="Activar" class="submit activa">
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock contenido %}

{% block extra_js %}

<script>
$(document).on("ready",inicio);

function inicio(){
	$("#id_membresia").on("keypress",function(e){
		return soloNumeros(e);
	});
}

function soloNumeros(evt){
	//asignamos el valor de la tecla a keynum
	if(window.event){// IE
		keynum = evt.keyCode;
	}else{
		keynum = evt.which;
	}
	//comprobamos si se encuentra en el rango
	if(keynum>47 && keynum<58){
		return true;
	}else{
		return false;
	}
}

</script>
	
{% endblock extra_js %}

django/access/access/templates/forms/membresia/reset_pass.html
{% extends "base/template_base.html" %}

{% block title %} Edicion de Perfil {% endblock %}

{% block contenido %}
	<div class="separador-slider visible-desktop"></div>
	<div class="container">
	    <div class="row">
	        	<h1 class="mod-head"><span id="msg">Contraseña</span></h1>
	        	<div class="form-full">
				
{% if msg %}
<div class="offset2 span8 ">
	<h3>{{msg}} <a class='btn btn-large btn-danger' href=" {% url edicion_membresia %} ">Regresar</a></h3>
</div>
{% else %}
				<form action="" method="POST">
					{% csrf_token %}
				<div class="offset4 span4">
					<fieldset>
					<h3 class="mod-head">Modificar contraseña</h3>
						{# Print form username and password #}
						
							

							{% for f in frm  %}
								
								<div class="control-group {% if f.errors %}error{% endif %}">
									<label class="control-label {% if f.errors %}error{% endif %}">
										{{f.label_tag}}
									</label>
									<div class="controls">
										{{ f }}
										{% if f.errors %}
											<span class="help-inline">{{f.errors}}</span>
										{% endif %}
									</div>
								</div>
							{% endfor %}	
						
								
					</fieldset>
				</div>
				<div class="full">
					<input type="submit" value="Guardar nueva contraseña" class="submit">
				</div>
				</form>
{% endif %}
			</div>
		</div>
	</div>
</div>
{% endblock contenido %}
{% block extra_js %}

<script type="text/javascript">
function soloNumeros(evt){
	//asignamos el valor de la tecla a keynum
	if(window.event){// IE
		keynum = evt.keyCode;
	}else{
		keynum = evt.which;
	}
	//comprobamos si se encuentra en el rango
	if(keynum>47 && keynum<58){
		return true;
	}else{
		return false;
	}
}

function inicio()
{
	$("#id_tipo").val({{tipo}});
	var texto = $("#id_tipo").find("option:selected").text();
	$("#msg").html("Compra de membresia Call Center " + texto);

	$("#id_cp").attr("maxlength","5");
	$("#id_area").attr("maxlength","3");
	$("#id_lada").attr("maxlength","3");
	$("#id_telefono").attr("maxlength","8");


	$("#id_cp").on("keypress",function(e){
		return soloNumeros(e);
	});
	$("#id_lada").on("keypress",function(e){
		return soloNumeros(e);
	});
	$("#id_area").on("keypress",function(e){
		return soloNumeros(e);
	});
	$("#id_telefono").on("keypress",function(e){
		return soloNumeros(e);
	});
}
$(document).on("ready",inicio);



</script>	
{% endblock extra_js %}

django/access/access/templates/forms/membresia/update_info.html
update_info.html