django/access/access/apps/citas/urls.py
from django.conf.urls.defaults import patterns,url

urlpatterns = patterns('access.apps.citas.views',
    url(r'^citas/$','citas',name='citas_view'),

    url(r'^citas/vuelo/$','citas_vuelo',name='citas_vuelo_view'),
    url(r'^citas/usuario/$','citas_usuario',name='citas_usuario_view'),
    url(r'^citas/confirmada/$','citas_confirmada',name='citas_confirmada_view'),

    url(r'^citas.solicitar/$','crear_cita',name='solicita_citas_view'),
    url(r'^citas.accion/$','accion_citas',name='accion_cita_view'),
    url(r'^citas.editar/(\d{1,6})/$','edita_citas',name='accion_cita_view'),
    url(r'^citas.ver/$','ver_todas_citas',name='ver_todas_citas'),
    url(r'^citas.ver/(\d{1,6})/$','ver_una_cita',name='ver_una_cita'),
   
    url(r'^citas.vuelo/(\d{1,6})/$','add_vuelo',name='add_vuelo'),
    
    url(r'^citas.filtros/$','citas_filtros',name='get_citas_filtros'),
    url(r'^citas.filtros/all$','citas_filtros_all',name='get_citas_filtros_all'),
    
    url(r'^citas.confirma/(\d{1,6})/$','confirma_cita',name='confirma_cita_view'),

    url(r'^citas.calendario/$','calendario_citas',name='calendario_cita'),

)

django/access/access/apps/inicio/urls.py
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('access.apps.inicio.views',
	url(r'^$', 'inicio',name='vista_inicio'),
    url(r'^contact/$','contact_view',name='contact_view'),

)

django/access/access/apps/usuarios/urls.py
from django.conf.urls.defaults import patterns,url

urlpatterns = patterns('access.apps.usuarios.views',
	 url(r'^usuarios/registro/$','registro_usuarios',name='registro_usuarios_view'),
     url(r'^usuarios/login/$','login_view',name='view_login'),
     url(r'^usuarios/info.adicional/$','llenar_info_adicional',name='info_adicional_view'),
     url(r'^usuarios/logout/$','logout_view',name='logout_liga_view'),
)

django/access/access/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required
import settings
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'access.views.home', name='home'),
    # url(r'^access/', include('access.foo.urls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
	# Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    # Our url's apps
    url(r'^static/media/(?P<path>.*)$','django.views.static.serve',{'document_root':settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$','django.views.static.serve',{'document_root':settings.STATIC_ROOT}),
    # (r'^comments/', include('django.contrib.comments.urls')),

    #Import urls.py's apps 
    url(r'^',include('access.apps.inicio.urls')),
    url(r'^',include('access.apps.usuarios.urls')),
    url(r'^',include('access.apps.membresias.urls')),
    url(r'^',include('access.apps.citas.urls')),
    url(r'^',include('access.apps.actividades.urls')),

)

django/access/access/apps/actividades/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.



class actividad(models.Model):
	miembro   = models.ForeignKey(User,related_name='miembros')
	descripcion = models.TextField()
	fecha     = models.DateTimeField(auto_now_add=True)
	leido     = models.BooleanField(default=False)
	def __unicode__(self):
		return "%s" % self.fecha

django/access/access/apps/citas/models.py
#encoding:utf-8
from django.db import models
from django.contrib.auth.models import User
from django import forms
# Modelos
from access.apps.membresias.models import membresia

class especialidad(models.Model):
	especialidad  = models.CharField(max_length=150,verbose_name="Especialidad")
	
	def __unicode__(self):
		return "%s" % self.especialidad
	class Meta:
		verbose_name = "Especialidad para citas"
		verbose_name_plural = "Especialidades para las citas"


class cita(models.Model):
	''' Modelo para la creación de citas '''
	# Relacionarla con datos de contacto y  problemas
	no_membresia			= models.ForeignKey(membresia)

	es_titular 				= models.BooleanField(default=False,verbose_name='¿Es el titular de la membresía?')
	
	relacion_titular 		= models.CharField(max_length=255,null=True,blank=True,verbose_name='¿Cuál es la relación con el titular de la membresía?')
	nombre_completo			= models.CharField(max_length=255,null=True,blank=True,verbose_name='Nombre completo de quién solicita la cita')
	datos_contacto			= models.TextField(null=True,blank=True,verbose_name='Datos de contacto, de quién solicita la cita')
		
	fecha_cita				= models.DateField(null=False,blank=False,verbose_name='Fecha aproximada de la cita')
	preferencia_horario 	= (("Manana","Mañana"),("Tarde","Tarde"),)
	preferencia				= models.CharField(max_length=50,choices=preferencia_horario,verbose_name="Preferencia de horario")

	especialidad_cita		= models.ForeignKey(especialidad,verbose_name='Especialidad para la cita',help_text="Si no conoces tu especialidad selecciona medicina interna.")
	especialidad_cita_otra	= models.CharField(max_length=255,verbose_name='Agregue la otra especialidad.',null=True,blank=True)
	motivos_cita			= models.TextField(null=True,blank=True,verbose_name='Motivos de tu cita',help_text="Ser tan amplio como puedas")
	
	estudios_fechas			= models.TextField(null=True,blank=True,verbose_name='Si tiene estudios previos, mencione cuales y en que fecha se revisaron')

	uso_poliza				= models.BooleanField(default=False,verbose_name='¿Harás uso de tu póliza de seguro? (Le recomendamos llenar los formularios que hablan de su póliza)')
	recomendaciones			= models.BooleanField(default=False, verbose_name = "¿Has leido las recomendaciones?")

	atendido_huston			= models.BooleanField(default=False,verbose_name='¿Ha recibido alguna vez tratamiento o atencion medica en el TMC?')
	donde					= models.CharField(max_length=255,verbose_name='¿En donde te atendieron?',null=True,blank=True)
	cuando					= models.DateField(verbose_name='¿En que fecha te atendieron?',null=True,blank=True)

	comentarios 			= models.TextField(verbose_name='Comentarios adicionales',null=True,blank=True)
	
	confirmada				= models.BooleanField(default=False)
	fecha_confirmada 		= models.DateTimeField(null=True,blank=True,verbose_name='Fecha y Hora confirmada para la cita en Houston')
	conf_miembro 			= models.BooleanField(default=False)

	fecha_hora 				= models.DateTimeField(auto_now_add=True)
	estado					= models.BooleanField(default=False)

	socio     				= models.ForeignKey(User,related_name="Socio",null=True,blank=True)
	miembro   				= models.ForeignKey(User,related_name="Membresia",null=True,blank=True)

	class Meta:
		verbose_name = 'Cita'
		verbose_name_plural = 'Citas'
	
	def __unicode__(self):
		return "Fecha Solicitada %s" % self.fecha_cita



class Vuelo(models.Model):
	Cita = models.ForeignKey(cita,related_name="citas",unique=True)
	HoraFecha = models.DateTimeField(verbose_name="Fecha y Hora")
	Aerolinea = models.CharField(max_length=100)
	Vuelo = models.CharField(max_length=100,verbose_name="Numero de Vuelo")
	Comentarios = models.TextField(verbose_name="Comentarios adicionales")
	Estado 	= models.BooleanField(default=False)
    
	class Meta:
	    verbose_name = 'vuelo'
	    verbose_name_plural = 'vuelos'

	def __unicode__(self):
	    return "%s" % self.Cita 
    



		

	

django/access/access/apps/inicio/models.py
from django.db import models

# Create your models here.

django/access/access/apps/servicios/models.py
from django.db import models

# Create your models here.

django/access/access/apps/actividades/forms.py
from django import forms
from django.forms import ModelForm
from django.db import models
from django.forms import ModelChoiceField




# class frmCita(forms.ModelForm):
# 	class Meta:
# 		model = cita
# 		exclude = ['no_membresia','confirmada','socio','miembro','estado',]


# class frmCitaAvion(forms.ModelForm):
# 	class Meta:
# 		model = cita
# 		fields = ['info_vuelo',]

django/access/access/apps/citas/forms.py
#encoding:utf-8

from django import forms
from django.forms import ModelForm
from django.db import models
from django.forms import ModelChoiceField
from access.apps.citas.models import cita,Vuelo



class frmCita(forms.ModelForm):
	class Meta:
		model = cita
		exclude = ['recomendaciones','no_membresia','confirmada','socio','miembro','estado','fecha_confirmada']


class frmCitaAvion(forms.ModelForm):
	class Meta:
		model = cita
		fields = ['recomendaciones',]


class frmAddInfoVuelo(forms.ModelForm):
	class Meta:
		model = Vuelo
		exclude = ['Cita','Estado']

django/access/access/apps/inicio/forms.py
from django import forms


class ContactForm(forms.Form):
	Name  		= forms.CharField(widget=forms.TextInput())
	Email 		= forms.EmailField(widget=forms.TextInput())
	Subject 	= forms.CharField(widget=forms.TextInput())
	Content 	= forms.CharField(widget=forms.Textarea())

django/access/access/apps/actividades/views.py
#encoding:utf-8
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from django.http import HttpResponse , HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
#Modelos 
from django.contrib.auth.models import User
from access.apps.actividades.models import actividad
# Formularios

# Librerias / Herramientas
from django.core.mail import EmailMultiAlternatives 

@login_required
def actividades_all(request):
	objActividades = actividad.objects.filter(miembro=request.user).order_by('-fecha')
	ctx = {"acts":objActividades}
	return render_to_response('actividades/actividades.html',ctx,context_instance=RequestContext(request))


@login_required
def ver_actividad(request,idActividad):
	idAct = int(idActividad)
	objAct = get_object_or_404(actividad,pk=idAct)
	ctx = {"act":objAct}
	return render_to_response('actividades/actividad.html',ctx,context_instance=RequestContext(request))

django/access/access/apps/inicio/views.py
from django.shortcuts 			import render_to_response
from django.template  			import RequestContext
from django.core.mail 			import EmailMultiAlternatives 
from django.http				import HttpResponseRedirect
from access.apps.inicio.forms 	import ContactForm



def inicio(request):
	return render_to_response('inicio/home.html',context_instance=RequestContext(request))

def contact_view(request):
	info_send = False # Define si se envio la info o no se envio
	name   = ""
	email  = ""
	subject = ""
	content  = ""
	if request.method == "POST":
		objForm = ContactForm(request.POST)
		if objForm.is_valid():
			info_send  = True
			name    = objForm.cleaned_data['Name']
			email   = objForm.cleaned_data['Email']
			subject = objForm.cleaned_data['Subject']
			content = objForm.cleaned_data['Content']
			# Configuracion para envio de email por gmail
			to_admin = 'roberto@newemage.com'
			html_content = "Information received from <br>Name: [%s] <br> Email: [%s]  <br><br>***Message<br><br>%s"%(name,email,content)
			msg = EmailMultiAlternatives(subject,html_content,'from@server.com',[to_admin])
			msg.attach_alternative(html_content,'text/html') #Definimos el contenido como HTML
			msg.send() #enviamos el correo
	else:
		objForm = ContactForm()
	ctx = {'form':objForm,'name':name,'email':email,'subject':subject,'content':content,'info_send':info_send}
	return render_to_response('forms/contact/contact.html',ctx,context_instance=RequestContext(request))	

django/access/access/apps/servicios/views.py
# Create your views here.

django/access/access/apps/usuarios/views.py
#encoding:utf-8
from django.shortcuts import render_to_response,get_object_or_404
from django.http import HttpResponseRedirect,HttpResponse
from django.template import RequestContext
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
# Models
from django.contrib.auth.models import User
from access.apps.usuarios.models import UserProfile
from access.apps.usuarios.forms import frmPerfil,UserForm,LoginForm
from django.contrib.auth.forms import UserCreationForm
from django.core.mail 			import EmailMultiAlternatives 

def login_view(request):
	strMsg =""
	if request.user.is_authenticated():
		return HttpResponseRedirect('/')
	else:
		if request.method == "POST":
			objForm = LoginForm(request.POST)
			if objForm.is_valid():
				username = objForm.cleaned_data['username']
				password = objForm.cleaned_data['password']
				objUser = authenticate(username=username,password=password)
				if objUser is not None and objUser.is_active:
					login(request,objUser)
					user_type = int(objUser.profile.tipo_usuario)
					url_redirect = ""
					if   user_type == 4:
						url_redirect = "/admin/"
					else:
						url_redirect = "/citas/"					
					return HttpResponseRedirect(url_redirect)
				else:
					strMsg = "Usuario ó contraseña incorrecto"
		objForm = LoginForm()
		ctx = {'form': objForm,'msg':strMsg}
		return render_to_response('forms/usuarios/login.html',ctx,context_instance=RequestContext(request))


def logout_view(request):
	logout(request)
	return HttpResponseRedirect('/')


def llenar_info_adicional(request):
	if request.method == "POST":
		frm = frmInfoAdicional(request.POST)
		if frm.is_valid():
			frmUncommit = frm.save(commit=False)
			frmUncommit.usuario = request.user
			frmUncommit.save()
			test = get_object_or_404(info_adicional,usuario=request.user)
			frm = frmInfoAdicional(instance=test)
			ctx = {'formAdicional':frm}
			return render_to_response('forms/usuarios/infoAdicional.html',ctx,context_instance=RequestContext(request))
		else:
			ctx = {'formAdicional':frm}
			return render_to_response('forms/usuarios/infoAdicional.html',ctx,context_instance=RequestContext(request))

	frm = frmInfoAdicional()
	ctx = {'formAdicional':frm}
	return render_to_response('forms/usuarios/infoAdicional.html',ctx,context_instance=RequestContext(request))


def registro_usuarios(request):
	if request.user.is_authenticated():
		return HttpResponseRedirect("/")
	
	if request.method == "POST":
		createFrm 	= UserCreationForm(request.POST)
		userFrm 	= UserForm(request.POST)
		perfil  	= frmPerfil(request.POST)
		if createFrm.is_valid() and userFrm.is_valid() and perfil.is_valid():
			username_ 			= createFrm.cleaned_data['username']
			password_ 			= createFrm.cleaned_data['password1']
			email_ 				= userFrm.cleaned_data['email']
			new_user 			= User.objects.create_user(username= username_, email= email_,password=password_)
			new_user.is_staff 	= False
			new_user.first_name = userFrm.cleaned_data['first_name']
			new_user.last_name 	= userFrm.cleaned_data['last_name']
			new_user.save()
			''' Add data to UserProfile model '''
			new_profile 					= UserProfile.objects.get(user=new_user)
			new_profile.genero 				= perfil.cleaned_data['genero']
			new_profile.fecha_nacimiento 	= perfil.cleaned_data['fecha_nacimiento']
			new_profile.estado_civil 		= perfil.cleaned_data['estado_civil']
			new_profile.hijos_menores_edad 	= perfil.cleaned_data['hijos_menores_edad']
			new_profile.calle 				= perfil.cleaned_data['calle']
			new_profile.no_exterior 		= perfil.cleaned_data['no_exterior']
			new_profile.no_interior 		= perfil.cleaned_data['no_interior']
			new_profile.colonia 			= perfil.cleaned_data['colonia']
			new_profile.municipio 			= perfil.cleaned_data['municipio']
			new_profile.ciudad 				= perfil.cleaned_data['ciudad']
			new_profile.estado 				= perfil.cleaned_data['estado']
			new_profile.cp 					= perfil.cleaned_data['cp']
			new_profile.telefono 			= perfil.cleaned_data['telefono']
			new_profile.save()
			""" Envia correo para el llenado de la siguiente información"""
			to_user = email_
			subject = "Activa membresia 24access"
			html_content = "Bienvenido al sistema 24access, por favor complete la información de registro para activar su membresia <br/> <a href='http://desarrollo.servebeer.com:8888/usuarios/login/' >Click aquí</a> O bien, copie y pegue esta liga en su navegador http://desarrollo.servebeer.com:8888/usuarios/login/ "
			msg = EmailMultiAlternatives(subject,html_content,'from@server.com',[to_user])
			msg.attach_alternative(html_content,'text/html') #Definimos el contenido como HTML
			msg.send() #enviamos el correo

			return HttpResponseRedirect('/')
		else:
			ctx={"frmPer":perfil,"frmUser":userFrm,'frmCreate':createFrm}
			return render_to_response('forms/usuarios/registro.html',ctx,context_instance=RequestContext(request))

	_create    = UserCreationForm()
	_frmPerfil = frmPerfil()
	_frmUser   = UserForm()
	ctx={"frmPer":_frmPerfil,"frmUser":_frmUser,'frmCreate':_create}
	return render_to_response('forms/usuarios/registro.html',ctx,context_instance=RequestContext(request))

django/access/access/templates/citas/edita_vuelo.html
{% extends "base/template_base.html" %}

{% block title %} Solicitar Cita {% endblock %}
{% block extra_css %}
	<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.0/themes/base/jquery-ui.css" />
{% endblock extra_css %}
{% block contenido %}
<div class="separador-slider visible-desktop"></div>
	<div class="container">
	    <div class="row">
	        <div class="span12">
	        	<h1 class="mod-head"><span>Información de vuelo</span></h1>
				<br><br>
				<a href="/citas/">Regresar a las citas</a>
				<form id="frmCita" action="." method="POST">
					{% csrf_token %}
					{{ form.as_p }}
					<input id="btnEnviar" class="btn btn-danger" type="submit" value="Guardar info de vuelo">
				</form>
				<a href="/citas/">Regresar a las citas</a> 
			</div>
		</div>
	</div>
</div>
{% endblock contenido %}

{% block extra_js %}
<script src="http://code.jquery.com/ui/1.10.0/jquery-ui.js"></script>
<script src=" {{ STATIC_URL }}js/plugins.js "></script>

<script>
	$('#id_HoraFecha').datetimepicker({ dateFormat: "dd/mm/yy" });
</script>
<style>
.ui-timepicker-div .ui-widget-header { margin-bottom: 8px; }
.ui-timepicker-div dl { text-align: left; }
.ui-timepicker-div dl dt { height: 25px; margin-bottom: -25px; }
.ui-timepicker-div dl dd { margin: 0 10px 10px 65px; }
.ui-timepicker-div td { font-size: 90%; }
.ui-tpicker-grid-label { background: none; border: none; margin: 0; padding: 0; }

.ui-timepicker-rtl{ direction: rtl; }
.ui-timepicker-rtl dl { text-align: right; }
.ui-timepicker-rtl dl dd { margin: 0 65px 10px 10px; }
</style>	
{% endblock extra_js %}

django/access/access/templates/citas/nueva_cita.html
{% extends "base/template_base.html" %}

{% block title %} Solicitar Cita {% endblock %}

{% block extra_css %}
	<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.0/themes/base/jquery-ui.css" />
{% endblock extra_css %}

{% block contenido %}
<div class="separador-slider visible-desktop"></div>
	<div class="container">
	    <div class="row">

	        	<h1 class="mod-head"><span>Solicita una cita</span></h1>
				<br><br>
				<div class="form-full">
				<form id="" action="." method="POST">
					{% csrf_token %}

					<div class="span5">
						<fieldset>

						<div class="control-group {% if form.es_titular.errors %}error{% endif %}">
							<div class="controls check">
							<label class="control-label">
								{{form.es_titular.label_tag}}
							</label>
							
								{{ form.es_titular }}
								{% if form.es_titular.errors %}
									<span class="help-inline">{{form.es_titular.errors}}</span>
								{% endif %}
							</div>
						</div>

						<div class="rel_titular control-group {% if form.relacion_titular.errors %}error{% endif %}">
							<label class="control-label">
								{{form.relacion_titular.label_tag}}
							</label>
							<div class="controls">
								{{ form.relacion_titular }}
								{% if form.relacion_titular.errors %}
									<span class="help-inline">{{form.relacion_titular.errors}}</span>
								{% endif %}
							</div>
						</div>

						<div class="rel_titular control-group {% if form.nombre_completo.errors %}error{% endif %}">
							<label class="control-label">
								{{form.nombre_completo.label_tag}}
							</label>
							<div class="controls">
								{{ form.nombre_completo }}
								{% if form.nombre_completo.errors %}
									<span class="help-inline">{{form.nombre_completo.errors}}</span>
								{% endif %}
							</div>
						</div>

						<div class="rel_titular control-group {% if form.datos_contacto.errors %}error{% endif %}">
							<label class="control-label">
								{{form.datos_contacto.label_tag}}
							</label>
							<div class="controls">
								{{ form.datos_contacto }}
								{% if form.datos_contacto.errors %}
									<span class="help-inline">{{form.datos_contacto.errors}}</span>
								{% endif %}
							</div>
						</div>
					<div class="position-two">
						
						<div class="control-group {% if form.fecha_cita.errors %}error{% endif %}">
							<label class="control-label">
								{{form.fecha_cita.label_tag}}
							</label>
							<div class="controls">
								{{ form.fecha_cita }}
								{% if form.fecha_cita.errors %}
									<span class="help-inline">{{form.fecha_cita.errors}}</span>
								{% endif %}
							</div>
						</div>
						<div class="control-group nopad {% if form.preferencia.errors %}error{% endif %}">
							<label class="control-label">
								{{form.preferencia.label_tag}}
							</label>
							<div class="controls">
								{{ form.preferencia }}
								{% if form.preferencia.errors %}
									<span class="help-inline">{{form.preferencia.errors}}</span>
								{% endif %}
							</div>
						</div>

						<div class="control-group nopad {% if form.hora_cita.errors %}error{% endif %}">
							<label class="control-label">
								{{form.hora_cita.label_tag}}
							</label>
							<div class="controls">
								{{ form.hora_cita }}
								{% if form.hora_cita.errors %}
									<span class="help-inline">{{form.hora_cita.errors}}</span>
								{% endif %}
							</div>
						</div>
					</div>
						<div class="control-group {% if form.especialidad_cita.errors %}error{% endif %}">
							<label class="control-label">
								{{form.especialidad_cita.label_tag}}
							</label>
							<div class="controls">
								{{ form.especialidad_cita }}
								{% if form.especialidad_cita.errors %}
									<span class="help-inline">{{form.especialidad_cita.errors}}</span>
								{% endif %}
								{% if form.especialidad_cita.help_text %}
									<span class="help-inline">{{form.especialidad_cita.help_text}}</span>
								{% endif %}
							</div>
						</div>

						<div class="control-group motivos {% if form.motivos_cita.errors %}error{% endif %}">
							<label class="control-label">
								{{form.motivos_cita.label_tag}}
							</label>
							<div class="controls">
								{{ form.motivos_cita }}
								{% if form.motivos_cita.errors %}
									<span class="help-inline">{{form.motivos_cita.errors}}</span>
								{% endif %}
								{% if form.motivos_cita.help_text %}
									<span class="help-inline">{{form.motivos_cita.help_text}}</span>
								{% endif %}
							</div>
						</div>

						</fieldset>
					</div>

					<div class="span5">
					<fieldset>

					<div class="control-group {% if form.estudios_fechas.errors %}error{% endif %}">
						<label class="control-label">
							{{form.estudios_fechas.label_tag}}
						</label>
						<div class="controls">
							{{ form.estudios_fechas }}
							{% if form.estudios_fechas.errors %}
								<span class="help-inline">{{form.estudios_fechas.errors}}</span>
							{% endif %}
						</div>
					</div>					

					<div class="control-group {% if form.uso_poliza.errors %}error{% endif %}">
						<div class="controls check">
						<label class="control-label">
							{{form.uso_poliza.label_tag}}
						</label>
						
							{{ form.uso_poliza }}
							{% if form.uso_poliza.errors %}
								<span class="help-inline">{{form.uso_poliza.errors}}</span>
							{% endif %}
						</div>
					</div>


					<div class="control-group {% if form.atendido_huston.errors %}error{% endif %}">
						<div class="controls check">
						<label class="control-label">
							{{form.atendido_huston.label_tag}}
						</label>
							{{ form.atendido_huston }}
							{% if form.atendido_huston.errors %}
								<span class="help-inline">{{form.atendido_huston.errors}}</span>
							{% endif %}
						</div>
					</div>

					<div class="control-group {% if form.comentarios.errors %}error{% endif %}">
						<label class="control-label">
							{{form.comentarios.label_tag}}
						</label>
						<div class="controls">
							{{ form.comentarios }}
							{% if form.comentarios.errors %}
								<span class="help-inline">{{form.comentarios.errors}}</span>
							{% endif %}
						</div>
					</div>


					</fieldset>
					
					</div>
					<div class="full-button">
						<input id="btnEnviar" class="submit activa" type="submit" value="Solicitar Cita">						
					</div>
						<!--{{ form.as_p }}-->

					
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock contenido %}

{% block extra_js %}
<script src="http://code.jquery.com/ui/1.10.0/jquery-ui.js"></script>
<script >
function oc(id,tf){
	if(tf){
		$("#" + id).hide().prev("label").hide();
	}else{
		$("#" + id).show().prev("label").show();
	}
}
function oculta_muestra(){
	var flag = $(this).is(":checked");
	if(flag){
		$(".rel_titular").fadeOut();
	}else{
		$(".rel_titular").fadeIn();
	}
}

function muestra_otro(){
	var valor = $(this).find("option:selected").text();
	if (valor == "otros" || valor == "otro" || valor == "otra" || valor == "otras"){
		$("#id_especialidad_cita_otra").show().prev("label").show();
	}else{
		$("#id_especialidad_cita_otra").hide().prev("label").hide();
	}
}
function ocultaInfo(){
	oc("id_donde",true);
	oc("id_cuando",true);
}
function muestra_oculta(estado){
	var flag = $(this).is(":checked");

	if(flag){
		oc("id_donde",false);
		oc("id_cuando",false);
	}else{
		oc("id_donde",true);
		oc("id_cuando",true);
	}
	
}
function check_edit(){
	var flag_titular = $("#id_es_titular").is(':checked');
	if( flag_titular ){
			$(".rel_titular").hide();
	}
	{% if editar %}
	var flag = 'true';
	{% else %}
	var flag = 'false';
	{% endif %}
	
	if(flag == 'true'){
		$("#btnEnviar").val("Guardar cambios");

	}

}
function inicio(){
	$("#id_es_titular").click();
	$("#id_es_titular").on("click",oculta_muestra);
	$("#id_especialidad_cita_otra").hide().prev("label").hide();
	$("#id_especialidad_cita").on("change",muestra_otro);
	
	ocultaInfo();
	
	$("#id_atendido_huston").on("click",muestra_oculta);
	check_edit()
	
	$.datepicker.setDefaults( $.datepicker.regional[ "es" ] );
	
	$("#id_fecha_cita").datepicker({ dateFormat: "dd/mm/yy" });
}

$(document).on("ready",inicio);
</script>
{% endblock extra_js %}