django/access/access/apps/citas/urls.py
from django.conf.urls.defaults import patterns,url

urlpatterns = patterns('access.apps.citas.views',
    url(r'^citas/$','citas',name='citas_view'),

    url(r'^citas/vuelo/$','citas_vuelo',name='citas_vuelo_view'),
    url(r'^citas/usuario/$','citas_usuario',name='citas_usuario_view'),
    url(r'^citas/confirmada/$','citas_confirmada',name='citas_confirmada_view'),

    url(r'^citas.solicitar/$','crear_cita',name='solicita_citas_view'),
    url(r'^citas.accion/$','accion_citas',name='accion_cita_view'),
    url(r'^citas.editar/(\d{1,6})/$','edita_citas',name='accion_cita_view'),
    url(r'^citas.ver/$','ver_todas_citas',name='ver_todas_citas'),
    url(r'^citas.ver/(\d{1,6})/$','ver_una_cita',name='ver_una_cita'),
   
    url(r'^citas.vuelo/(\d{1,6})/$','add_vuelo',name='add_vuelo'),
    
    url(r'^citas.filtros/$','citas_filtros',name='get_citas_filtros'),
    url(r'^citas.filtros/all$','citas_filtros_all',name='get_citas_filtros_all'),
    
    url(r'^citas.confirma/(\d{1,6})/$','confirma_cita',name='confirma_cita_view'),

    url(r'^citas.calendario/$','calendario_citas',name='calendario_cita'),

)

django/access/access/apps/inicio/urls.py
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('access.apps.inicio.views',
	url(r'^$', 'inicio',name='vista_inicio'),
    url(r'^contact/$','contact_view',name='contact_view'),

)

django/access/access/apps/usuarios/urls.py
from django.conf.urls.defaults import patterns,url

urlpatterns = patterns('access.apps.usuarios.views',
	 url(r'^usuarios/registro/$','registro_usuarios',name='registro_usuarios_view'),
     url(r'^usuarios/login/$','login_view',name='view_login'),
     url(r'^usuarios/info.adicional/$','llenar_info_adicional',name='info_adicional_view'),
     url(r'^usuarios/logout/$','logout_view',name='logout_liga_view'),
)

django/access/access/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required
import settings
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'access.views.home', name='home'),
    # url(r'^access/', include('access.foo.urls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
	# Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    # Our url's apps
    url(r'^static/media/(?P<path>.*)$','django.views.static.serve',{'document_root':settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$','django.views.static.serve',{'document_root':settings.STATIC_ROOT}),
    # (r'^comments/', include('django.contrib.comments.urls')),

    #Import urls.py's apps 
    url(r'^',include('access.apps.inicio.urls')),
    url(r'^',include('access.apps.usuarios.urls')),
    url(r'^',include('access.apps.membresias.urls')),
    url(r'^',include('access.apps.citas.urls')),
    url(r'^',include('access.apps.actividades.urls')),

)

django/access/access/apps/citas/models.py
#encoding:utf-8
from django.db import models
from django.contrib.auth.models import User
from django import forms
# Modelos
from access.apps.membresias.models import membresia

class especialidad(models.Model):
	especialidad  = models.CharField(max_length=150,verbose_name="Especialidad")
	
	def __unicode__(self):
		return "%s" % self.especialidad
	class Meta:
		verbose_name = "Especialidad para citas"
		verbose_name_plural = "Especialidades para las citas"


class cita(models.Model):
	''' Modelo para la creación de citas '''
	# Relacionarla con datos de contacto y  problemas
	no_membresia			= models.ForeignKey(membresia)

	es_titular 				= models.BooleanField(default=False,verbose_name='¿Es el titular de la membresía?')
	
	relacion_titular 		= models.CharField(max_length=255,null=True,blank=True,verbose_name='¿Cuál es la relación con el titular de la membresía?')
	nombre_completo			= models.CharField(max_length=255,null=True,blank=True,verbose_name='Nombre completo de quién solicita la cita')
	datos_contacto			= models.TextField(null=True,blank=True,verbose_name='Datos de contacto, de quién solicita la cita')
		
	fecha_cita				= models.DateField(null=False,blank=False,verbose_name='Fecha aproximada de la cita')
	preferencia_horario 	= (("Manana","Mañana"),("Tarde","Tarde"),)
	preferencia				= models.CharField(max_length=50,choices=preferencia_horario,verbose_name="Preferencia de horario")

	especialidad_cita		= models.ForeignKey(especialidad,verbose_name='Especialidad para la cita',help_text="Si no conoces tu especialidad selecciona medicina interna.")
	especialidad_cita_otra	= models.CharField(max_length=255,verbose_name='Agregue la otra especialidad.',null=True,blank=True)
	motivos_cita			= models.TextField(null=True,blank=True,verbose_name='Motivos de tu cita',help_text="Ser tan amplio como puedas")
	
	estudios_fechas			= models.TextField(null=True,blank=True,verbose_name='Si tiene estudios previos, mencione cuales y en que fecha se revisaron')

	uso_poliza				= models.BooleanField(default=False,verbose_name='¿Harás uso de tu póliza de seguro? (Le recomendamos llenar los formularios que hablan de su póliza)')
	recomendaciones			= models.BooleanField(default=False, verbose_name = "¿Has leido las recomendaciones?")

	atendido_huston			= models.BooleanField(default=False,verbose_name='¿Ha recibido alguna vez tratamiento o atencion medica en el TMC?')
	donde					= models.CharField(max_length=255,verbose_name='¿En donde te atendieron?',null=True,blank=True)
	cuando					= models.DateField(verbose_name='¿En que fecha te atendieron?',null=True,blank=True)

	comentarios 			= models.TextField(verbose_name='Comentarios adicionales',null=True,blank=True)
	
	confirmada				= models.BooleanField(default=False)
	fecha_confirmada 		= models.DateTimeField(null=True,blank=True,verbose_name='Fecha y Hora confirmada para la cita en Houston')
	conf_miembro 			= models.BooleanField(default=False)

	fecha_hora 				= models.DateTimeField(auto_now_add=True)
	estado					= models.BooleanField(default=False)

	socio     				= models.ForeignKey(User,related_name="Socio",null=True,blank=True)
	miembro   				= models.ForeignKey(User,related_name="Membresia",null=True,blank=True)

	class Meta:
		verbose_name = 'Cita'
		verbose_name_plural = 'Citas'
	
	def __unicode__(self):
		return "Fecha Solicitada %s" % self.fecha_cita



class Vuelo(models.Model):
	Cita = models.ForeignKey(cita,related_name="citas",unique=True)
	HoraFecha = models.DateTimeField(verbose_name="Fecha y Hora")
	Aerolinea = models.CharField(max_length=100)
	Vuelo = models.CharField(max_length=100,verbose_name="Numero de Vuelo")
	Comentarios = models.TextField(verbose_name="Comentarios adicionales")
	Estado 	= models.BooleanField(default=False)
    
	class Meta:
	    verbose_name = 'vuelo'
	    verbose_name_plural = 'vuelos'

	def __unicode__(self):
	    return "%s" % self.Cita 
    



		

	

django/access/access/apps/inicio/models.py
from django.db import models

# Create your models here.

django/access/access/apps/membresias/models.py
#encoding:utf-8
from django.db import models
from django.contrib.auth.models import User
from django import forms


class tipo_poliza(models.Model):
	tipo_poliza = models.CharField(max_length=150,verbose_name="Tipo de póliza")

	def __unicode__(self):
		return "%s" %self.tipo_poliza

	class Meta:
		verbose_name = "Tipo de Póliza"
		verbose_name_plural = "Tipos de Pólizas"

class tipo_cobertura(models.Model):
	cobertura = models.CharField(max_length=150,verbose_name="Tipo de cobertura")

	def __unicode__(self):
		return "%s" %self.cobertura

	class Meta:
		verbose_name = "Tipo de cobertura"
		verbose_name_plural = "Tipos de Coberturas"

	
class membresia(models.Model):
	''' Modelo para los diferentes tipos de membresia que tendra el sistema  [Individual,Familiar,Corporativo]'''
	membresia_tipo  = (("1","Personal"),("3","Corporativa"),)	
	sexo_tipo 		= (("Femenino","Femenino"),("Masculino","Masculino"),)
	''' Estos son los campos para la compra de la membresia '''
	tipo					= models.CharField(max_length=50,choices=membresia_tipo)
	
	nombre 					= models.CharField(null=False,blank=False, verbose_name='Nombre(s)', max_length=100)
	apellido_paterno 		= models.CharField(null=False,blank=False, verbose_name='Apellido Paterno', max_length=100)
	apellido_materno 	 	= models.CharField(null=False,blank=False, verbose_name="Apellido Materno", max_length=255)

	calle  					= models.CharField(verbose_name='Calle',max_length=100,null=True,blank=True)
	no_exterior				= models.CharField(verbose_name="No. Exterior",max_length=10,null=True,blank=True)
	no_interior	 			= models.CharField(verbose_name='No. Interior',max_length=10,blank=True,null=True)
	colonia					= models.CharField(verbose_name='Colonia',max_length=100,null=True,blank=True)
	municipio				= models.CharField(verbose_name='Delegación o Municipio',max_length=150,null=True,blank=True)
	ciudad					= models.CharField(verbose_name='Ciudad',max_length=100,null=True,blank=True)
	cp 						= models.IntegerField(verbose_name='CP.',null=True,blank=True)
	pais 					= models.CharField(verbose_name='País',max_length=150,null=True,blank=True)
	
	email 					= models.EmailField(null=False,blank=False, verbose_name='Email principal',max_length=200)
	re_email 		 		= models.EmailField(null=False,blank=False,verbose_name='Confirma tu Mail',max_length=200)
	
	area                    = models.CharField(verbose_name="Área internacinal",max_length=20,null=True,blank=True)
	lada				    = models.CharField(verbose_name='Clave Lada',max_length=20,null=True,blank=True)
	telefono				= models.CharField(verbose_name='Telefono',max_length=20,null=True,blank=True)

	''' Enlace a Miembro y Call Center '''
	call_center 			= models.ForeignKey(User,related_name='CallCenter',null=True,blank=True)
	miembro 	 			= models.ForeignKey(User,related_name='Miembro',null=True,blank=True)

	''' '''
	password 				= models.CharField(verbose_name='Contraseña',max_length=250)
	renovo_pass 			= models.BooleanField(default=False)
	online 					= models.BooleanField(default=False)
	padre                   = models.IntegerField(default=0,null=True,blank=True)

	fecha_registro			= models.DateField(auto_now_add=True)
	fecha_envio				= models.DateField(null=True,blank=True)
	fecha_recibo			= models.DateField(null=True,blank=True)
	activa 				    = models.BooleanField(default=False)
	pagada 					= models.BooleanField(default=False)
	activa_paquete  		= models.BooleanField(default=False)

	costo 					= models.FloatField(default=0,null=True,blank=True)

	class Meta:
		verbose_name = 'membresia'
		verbose_name_plural = 'membresias'
		
	def __unicode__(self):
		return "%s %s %s -- %s"%(self.nombre,self.apellido_paterno,self.apellido_materno, self.id) 

class MenoresEdad(models.Model):
	titular          = models.ForeignKey(User,related_name="Titulares")
	mem_titular      = models.ForeignKey(membresia,related_name="MemTitulares")
	nombre           = models.CharField(max_length=150,verbose_name="Nombre")
	apellido_paterno = models.CharField(max_length=150,verbose_name="Apellido Paterno")
	apellido_materno = models.CharField(max_length=150,verbose_name="Apellido Materno")
	fecha_nacimiento = models.DateField(verbose_name="Fecha de nacimiento")
	relacion 		 = models.CharField(null=True,blank=True,max_length=100,verbose_name="Relación con el titular")
	class Meta:
		verbose_name = 'Menor de edad'
		verbose_name_plural = 'Menores de edad'

	def __unicode__(self):
		return ("%s %s %s")%(self.nombre, self.apellido_materno,self.apellido_paterno)

class PaseMenor(models.Model):
	titular 		= models.ForeignKey(User,related_name='PasesTitulares')
	menor   		= models.ForeignKey(MenoresEdad,related_name='Pases',verbose_name="Seleccione el menor de edad")
	fecha_inicio    = models.DateField(auto_now_add=True) 
	fecha_fin   	= models.DateField() 
	
	def __unicode__(self):
		return ("%s %s %s")%(self.menor.nombre, self.menor.apellido_materno,self.menor.apellido_paterno)


class rel_mem(models.Model):
	titular      = models.ForeignKey(User,related_name="UsuarioTitular")
	mem_titular  = models.ForeignKey(membresia,related_name="MembresiaTitular")
	mem_referido = models.ForeignKey(membresia,related_name="MembresiaReferida")
	fecha_hora   = models.DateTimeField(auto_now_add=True)
	
	def __unicode__(self):
		return "%s %s -- %s" % (self.titular.first_name,self.titular.last_name,self.mem_referido)
	class Meta:
		verbose_name        = "Referidos Membresia"
		verbose_name_plural = "Sistema de Referidos"




class info_adicional(models.Model):
	''' Información requerida para la activación de las membresias. '''
	membresia 				= models.ForeignKey(membresia)
	
	compania_seguros	 	= models.CharField(max_length=255,verbose_name="Compañia de seguros")
	# Se quito direccion de compañia
	# direccion_compania	 	= models.TextField(blank=True,null=True,verbose_name="Dirección de la compañía de seguros")
	nombre_representante 	= models.CharField(max_length=255,verbose_name="Nombre del representante de compañía de seguros o intermediario",blank=True,null=True)
	telefono_representante 	= models.CharField(max_length=255,verbose_name="Telefono del representante de compañía de seguros",blank=True,null=True)
	 
	# Informacion de póliza
	poliza 					= models.CharField(max_length=255,verbose_name="Póliza")
	tipo_poliza 			= models.ForeignKey(tipo_poliza, verbose_name="Selecciona el tipo de póliza")
	tipo_cobertura 			= models.ForeignKey(tipo_cobertura, verbose_name="Selecciona el tipo de cobertura")
	# Se mostraran solo si selecionan la plabra otros dentro de los select anteriores
	tipo_poliza_otro 			= models.CharField(max_length=255,verbose_name="Tipo Póliza",blank=True,null=True)
	tipo_cobertura_otro 		= models.CharField(max_length=255,verbose_name="Tipo Cobertura | Plan",blank=True,null=True)
	fecha_vencimiento           = models.DateField(verbose_name="Fecha de Vencimiento")

	# Preguntar si son requeridos estos campos
	contacto_emergencia_usa  = models.CharField(max_length=255,verbose_name='Contacto de emergencia en USA',blank=True,null=True)
	telefono_contacto_usa    = models.CharField(verbose_name='Telefono del contacto en USA', max_length=50,blank=True,null=True)
	nombre_dr_mexico	     = models.CharField(verbose_name='Nombre de tu doctor en México', max_length=255,blank=True,null=True)
	telefono_dr_mexico	     = models.CharField(verbose_name='Teléfono de tu doctor en México', max_length=255,blank=True,null=True)
	info_adicional_tx_center = models.TextField(verbose_name='Información adicional solicitada por TX Medical Center',blank=True,null=True)

	# Tiene pasaporte, si no, esconde campos y no son requeridos
		# Se elemino la pregunta si tiene pasaporte o no.
	# tiene_pasaporte         = models.BooleanField(verbose_name="¿Tiene pasaporte?")
	no_pasaporte  		    = models.CharField(verbose_name='No. Pasaporte', max_length=255,blank=True,null=True)
		# vencimiento_pasaporte   = models.DateField(verbose_name='Fecha de vencimiento del pasaporte',blank=True,null=True)
	# Tiene visa? si no, oculta campos siguientes
	# tiene_visa  		    = models.BooleanField(verbose_name='¿Tiene VISA?', max_length=255)
	no_visa					= models.CharField(verbose_name='No. VISA', max_length=255,blank=True,null=True)
	# vencimiento_visa   		= models.DateField(verbose_name='Fecha de vencimiento de la VISA',blank=True,null=True)
	class Meta:
		verbose_name = 'Info. adicional para activación'
		verbose_name_plural = 'Información Adicional'
	
	def __unicode__(self):
		return "%s" %self.compania_seguros
    

class miembros_adicionales(models.Model):
	''' Modelo para la relación de miembros adicionales de cada titular de membresias '''
	sexo_tipo = (("Femenino","Femenino"),("Masculino","Masculino"),)

	membresia 			 	= models.ForeignKey(membresia,verbose_name="Seleccione la membresia",blank=True,null=True)

	nombre				 	= models.CharField(max_length=255,verbose_name="Nombre (s)")
	apellido_paterno 	 	= models.CharField(verbose_name="Apellido Paterno", max_length=255)
	apellido_materno 	 	= models.CharField(verbose_name="Apellido Materno", max_length=255)
	genero 				 	= models.CharField(verbose_name="Género", choices=sexo_tipo, max_length=10)
	nacionalidad		 	= models.CharField(max_length=100)
	fecha_nacimiento       	= models.DateField(verbose_name="Fecha de Nacimiento")
	parentesco			 	= models.CharField(max_length=255,verbose_name="¿Cúal es el parentesco con el titular de la membresia?")

	# Comparte Poliza? Si es False se muestran la info de captura de poliza.
	comparte_poliza      	= models.BooleanField(default=False)
	
	# Informacion del intermediario
	nombre_representante 	= models.CharField(max_length=255,verbose_name="Nombre del representante de compañía de seguros o intermediario",blank=True,null=True)
	telefono_representante 	= models.CharField(max_length=255,verbose_name="Telefono del representante de compañía de seguros",blank=True,null=True)
	# Información de póliza
	poliza 					= models.CharField(max_length=255,verbose_name="Póliza",blank=True,null=True)

django/access/access/apps/actividades/forms.py
from django import forms
from django.forms import ModelForm
from django.db import models
from django.forms import ModelChoiceField




# class frmCita(forms.ModelForm):
# 	class Meta:
# 		model = cita
# 		exclude = ['no_membresia','confirmada','socio','miembro','estado',]


# class frmCitaAvion(forms.ModelForm):
# 	class Meta:
# 		model = cita
# 		fields = ['info_vuelo',]

django/access/access/apps/inicio/forms.py
from django import forms


class ContactForm(forms.Form):
	Name  		= forms.CharField(widget=forms.TextInput())
	Email 		= forms.EmailField(widget=forms.TextInput())
	Subject 	= forms.CharField(widget=forms.TextInput())
	Content 	= forms.CharField(widget=forms.Textarea())

django/access/access/apps/servicios/views.py
# Create your views here.

django/access/access/templates/menores/nuevo.html
{% extends "base/template_base.html" %}

{% block title %} Agregar nuevo menor de edad {% endblock %}

{% block contenido %}
<div class="separador-slider visible-desktop"></div>
	<div class="container">
	    <div class="row">
	        	<h1 class="mod-head"><span>Agrega un nuevo menor</span></h1>
				<br><br>
				<div class="form-full">
				<div class="center-menor">
				<form id="" action="" method="POST">
					{% csrf_token %}
					<fieldset>
						<h3 class="mod-head"> Información del menor de edad</h3>
					
					{% for f in form  %}
						<div class="control-group  {% if f.errors %}error{% endif %}">
							<label class="control-label">
								{{f.label_tag}}
							</label>
							<div class="controls">
								{{ f }}
								{% if f.errors %}
									<span class="help-inline">{{f.errors}}</span>
								{% endif %}
							</div>
						</div>
					{% endfor %}
				
					</fieldset>
					</div>
					</div>
					<div class="full-button">
						<input id="btnEnviar" class="submit activa" type="submit" value="Guardar nuevo menor de edad">						
					</div>
						<!--{{ form.as_p }}-->

					
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock contenido %}

{% block extra_js %}
<script >
function oc(id,tf){
	if(tf){
		$("#" + id).hide().prev("label").hide();
	}else{
		$("#" + id).show().prev("label").show();
	}
}
function oculta_muestra(){
	var flag = $(this).is(":checked");
	if(flag){
		$(".rel_titular").fadeOut();
	}else{
		$(".rel_titular").fadeIn();
	}
}
function muestra_otro(){
	var valor = $(this).find("option:selected").text();
	if (valor == "otros" || valor == "otro" || valor == "otra" || valor == "otras"){
		$("#id_especialidad_cita_otra").show().prev("label").show();
	}else{
		$("#id_especialidad_cita_otra").hide().prev("label").hide();
	}
}
function ocultaInfo(){
	oc("id_donde",true);
	oc("id_cuando",true);
}
function muestra_oculta(estado){
	var flag = $(this).is(":checked");

	if(flag){
		oc("id_donde",false);
		oc("id_cuando",false);
	}else{
		oc("id_donde",true);
		oc("id_cuando",true);
	}
	
}
function check_edit(){
	var flag_titular = $("#id_es_titular").is(':checked');
	if( flag_titular ){
			$(".rel_titular").hide();
	}
	{% if editar %}
	var flag = 'true';
	{% else %}
	var flag = 'false';
	{% endif %}
	
	if(flag == 'true'){
		$("#btnEnviar").val("Guardar cambios");

	}

}
function inicio(){
	$("#id_es_titular").on("click",oculta_muestra);
	$("#id_especialidad_cita_otra").hide().prev("label").hide();
	$("#id_especialidad_cita").on("change",muestra_otro);
	ocultaInfo();
	$("#id_atendido_huston").on("click",muestra_oculta);
	check_edit()
}

$(document).on("ready",inicio);
</script>
{% endblock extra_js %}

django/access/access/templates/menores/pase.html
{% extends "base/template_base.html" %}

{% block title %} Comprar Pase para menor {% endblock %}

{% block contenido %}
<div class="separador-slider visible-desktop"></div>
	<div class="container">
	    <div class="row">
	        	<h1 class="mod-head"><span>Comprar pase para menor de edad</span></h1>
				<br><br>
				<div class="form-full">
				<div class="center-menor">
				<form id="" action="" method="POST">
					{% csrf_token %}
					<fieldset>
						<h3 class="mod-head">Compra de pase para un año</h3>
					
					{% if mensaje %}
						<div><h5>{{mensaje}}</h5></div>
						Fecha Compra: <strong>{{pase.fecha_inicio}}</strong> <br> 
						Fecha vencimiento: <strong>{{pase.fecha_fin}}</strong>
						<br>
					{% endif %}

						<div class="control-group  {% if f.menor.errors %}error{% endif %}">
							<label class="control-label">
								{{f.menor.label_tag}}
							</label>
							<div class="controls">
								<select name="menor" id="id_menor">
									<option value="" selected="selected">---------</option>
									{% for m in menores  %}
										<option value="{{m.id}}">{{m.name}} {{m.apellido_paterno}} {{m.apellido_materno}}</option>
									{% endfor %}
								</select>
								{% if f.menor.errors %}
									<span class="help-inline">{{f.menor.errors}}</span>
								{% endif %}
							</div>
						</div>
				
				
					</fieldset>
					</div>
					</div>
					<div class="full-button">
						<input id="btnEnviar" class="submit activa" type="submit" value="Comprar pase">						
					</div>
						<!--{{ form.as_p }}-->
				</form>

			</div>
		</div>
	</div>
</div>
{% endblock contenido %}

{% block extra_js %}
<script >
function oc(id,tf){
	if(tf){
		$("#" + id).hide().prev("label").hide();
	}else{
		$("#" + id).show().prev("label").show();
	}
}
function oculta_muestra(){
	var flag = $(this).is(":checked");
	if(flag){
		$(".rel_titular").fadeOut();
	}else{
		$(".rel_titular").fadeIn();
	}
}
function muestra_otro(){
	var valor = $(this).find("option:selected").text();
	if (valor == "otros" || valor == "otro" || valor == "otra" || valor == "otras"){
		$("#id_especialidad_cita_otra").show().prev("label").show();
	}else{
		$("#id_especialidad_cita_otra").hide().prev("label").hide();
	}
}
function ocultaInfo(){
	oc("id_donde",true);
	oc("id_cuando",true);
}
function muestra_oculta(estado){
	var flag = $(this).is(":checked");

	if(flag){
		oc("id_donde",false);
		oc("id_cuando",false);
	}else{
		oc("id_donde",true);
		oc("id_cuando",true);
	}
	
}
function check_edit(){
	var flag_titular = $("#id_es_titular").is(':checked');
	if( flag_titular ){
			$(".rel_titular").hide();
	}
	{% if editar %}
	var flag = 'true';
	{% else %}
	var flag = 'false';
	{% endif %}
	
	if(flag == 'true'){
		$("#btnEnviar").val("Guardar cambios");

	}

}
function inicio(){
	$("#id_es_titular").on("click",oculta_muestra);
	$("#id_especialidad_cita_otra").hide().prev("label").hide();
	$("#id_especialidad_cita").on("change",muestra_otro);
	ocultaInfo();
	$("#id_atendido_huston").on("click",muestra_oculta);
	check_edit()
}

$(document).on("ready",inicio);
</script>
{% endblock extra_js %}